# Generated by Django 5.1.7 on 2025-04-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib', '0002_borrowrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
