# Generated by Django 5.1.7 on 2025-04-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib', '0003_book_preview_link_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_book_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
